from pymongo import MongoClient

# Authors / Changes Made: TEAM D, COMP523 Fall 23

# this method needs to be called from the record_pistons function in Model.py
def update_database(current_date, interval_label, time_label, data):
    try:
        # connected to localhost
        client = MongoClient("mongodb://127.0.0.1:27017/", serverSelectionTimeoutMS=2000)

        # database is called wavemaker_db, collection is called general_collection
        # these will be the only database and collection created and will store all data
        db = client.wavemaker_db
        collection = db.general_collection

        # _id field is generated by MongoDB
        collection.insert_one({"Date": current_date, "Interval": interval_label, "Time": time_label, "Data": data})
        print(f"Successfully saved data to database for {current_date}")
    except Exception as e:
        print(f"Warning: Could not connect to MongoDB database. Data not saved. Error: {e}")
        # App continues to work without database



def query_database(query):
    # Format of query should be the following
    # query = {"date": "%m%D%Y %H:%M:%S"}

    try:
        # Connecting to database
        client = MongoClient("mongodb://127.0.0.1:27017/", serverSelectionTimeoutMS=2000)
        db = client.wavemaker_db
        collection = db.general_collection

        return collection.find(query)
    except Exception as e:
        print(f"Warning: Could not connect to MongoDB database. Query failed. Error: {e}")
        return []  # Return empty list if database unavailable


# Commented out to prevent automatic execution on import
# This allows the app to run without MongoDB for testing/mock mode
# Uncomment these lines if you want to test database connection directly
# runs = query_database({})
# for run in runs:
#     print(run)
